# 站点设置

#注意！设置您网站的url，否则将无法正常工作
网址：“https://le4ker.github.io/personal-jekyll-theme”

# 谷歌跟踪 ID
谷歌跟踪 ID：“UA-XXXXXXXX-X”

#############
#HTML头#
#############

郎：“恩”
作者：约翰·史密斯
标题：“{约翰·史密斯}”
描述：“约翰·史密斯的博客和网站，主要针对技术的博客。表达的意见是我的。”
关键词：“史密斯、琼斯、个人、杰基尔、主题”
图标：“/img/favicon.ico”
################
#标题布局#
################
黑色图标：“/img/black-lab-glass.ico”
背景-img：“简介-bg.jpg”

#################################################### ####
#标题上的动态文本#
#################################################### ##

引用：“你想在哪里产生奇怪的愿望吗？”
我-img：“/img/jetpacktocat.png”

# 要使用 github 配置文件图片，请取消注释以下行并替换 'user_name'
# 使用你的github用户名。

# me-img: "https://github.com/user_name.png?size=500"

# 要使用 gravatar 个人资料图片，请取消注释以下行并替换 'email_hash'
# 使用您的头像个人数据电子邮件存储值。
# 您可以使用“http://www.md5hashgenerator.com/”等在线工具创建电子邮件哈希
#输入您的电子邮件，它就会生成哈希值。

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

#######
＃ 博客 ＃
########

预览后字数：96
分页：5
电子邮件分享：正确
Facebook 分享：正确
推特分享：真实
linkedin 分享：正确
reddit 分享：真实
tumblr 分享：真实
pinterest 分享：真实
口袋共享：正确
vkontakte-share：正确

disqus-shortname：“个人杰基尔主题”

############
#时间轴#
############

事件：
  -图片：“/img/timeline/spidertocat.png”
    日期：“2013 年 9 月 - 今天”
    描述：“邻居邻居！”
  -图片：“/img/timeline/baracktocat.jpg”
    日期：“2007年9月-2013年8月”
    描述：“开始编码”

#时间线的第一张图片
时间线-img：“/img/timeline/default.png”

###########
＃接触＃
###########

电子邮件：“your@email.here”
# 这里设置一个指向您发布的 PGP 的 url，将会出现在“联系方式”部分
PGP：假

################
#作者简介#
################

# 作者简介位于博客文章下方。
#当您的作者简介图片具有透明背景或与您的网站背景颜色相匹配时，此方法效果最佳。

# 如果没有设置author_blurb，则跳过此功能
作者简介：
  “约翰·史密斯是一个了不起的人。他住在弗拉特兰，在那里研究二维码
  工程项目。闲暇时，约翰喜欢吃棉花糖。”
author_blurb_image: "/img/author.png"

##################
#社交按钮#
##################

社会的：
  - 图标：“github”
    网址：“https://github.com/le4ker/personal-jekyll-theme”
  - 图标：“linkedin-in”
    网址：“https://www.linkedin.com”
  - 图标：“x-twitter”
    网址：“https://twitter.com/”
  - 图标：“RSS”
    网址：“https://le4ker.github.io/personal-jekyll-theme/feed.xml”

#注意！如果您想更改此点以下的变量，请务必小心！

# 索引页中显示的部分
页面列表：
  关于：“关于”
  博客：“最新帖子”
  时间线：“时间线”
  联系方式：“联系方式”
# 生成的_site中的排除列表
排除：
  - 梦
  - 自述文件.md
  - 贡献
  - 贡献者
  - 脚本
  - Dockerfile
  - docker-compose.yml
# 分页路径
paginate_path: "博客/页面:num/"
# 启用SASS缩小
萨斯：
  风格: 压缩
插件：
  - 杰基尔分页
  - 杰基尔宇宙飞船
